### ISSUE TITLE
Is this library under any development?

### ISSUE THREAD

**Issue by kexoth** [webengineer-max/mnesia_ecto#2]
I'm sorry to write like this, but the last commit is over a year ago & yet this is something I'd like to see as a part of Ecto one day.

I'm here for help on this library if needed.

Thanks,
@kexoth

**Comment by webengineer-max** [comment]
Hi Aleksandar

No, this is not under development at now actually. Maybe check [ecto_mnesia](https://github.com/Nebo15/ecto_mnesia).

-- 
Max
